Repository keyteki/keyteki, pull requests merged in 2023-01, with the labels that each got.

#2890 Fix/alliance deck in normal archonte
  client/Components/Decks/DeckList.jsx
  server/services/DeckService.js
Labels: alliance

#2880 Fix/#2879 allow all decks in alliance
  client/Components/Games/PendingGame.jsx
Labels: alliance

#2853 Fixes some interactions with Armageddon Cloak
  server/game/cards/03-WC/TheColosseum.js
  server/game/cards/04-MM/LookOverThere.js
  test/server/cards/01-Core/SpecialDelivery.spec.js
  test/server/cards/03-WC/TheColosseum.spec.js
  test/server/cards/04-MM/LookOverThere.spec.js
Labels: low impact

#2857 Fixes Reclaimed by Nature being simultaneous.
  server/game/cards/04-MM/ReclaimedbyNature.js
  test/server/cards/04-MM/ReclaimedByNature.spec.js
Labels: low impact

#2854 Fixes effects not being applied when creatures put in play under opponent control after being purged by Spangler Box or General Sherman
  server/game/GameActions/PutIntoPlayAction.js
  test/server/cards/02-AoA/ScowlyCaper.spec.js
Labels: medium impact

#2861 Refactor how EffectContext is passed to Condition effect values.
  server/game/Effects/StaticEffect.js
  server/game/Effects/Values/CanUse.js
  server/game/Effects/Values/CannotRestriction.js
  server/game/Effects/Values/ConditionValue.js
  server/game/Effects/Values/EffectValue.js
  server/game/GameActions/PutIntoPlayAction.js
  server/game/GameObject.js
  server/game/costs.js
  test/server/cards/01-Core/PhaseShift.spec.js
  test/server/cards/03-WC/MimicGel.spec.js
Labels: high impact

#2862 Fixes wild bounty and fission bloom lasting effect
  server/game/cards/04-MM/FissionBloom.js
  server/game/cards/04-MM/WildBounty.js
  test/server/cards/04-MM/FissionBloom.spec.js
  test/server/cards/04-MM/MasterOfTheGrey.spec.js
  test/server/cards/04-MM/WildBounty.spec.js
Labels: medium impact

#2885 Elusive should be turned off if attacking creature is destroyed by opponent's hazardous
  server/game/GameActions/ResolveFightAction.js
  test/server/keywords.spec.js
Labels: high impact
